---
- hosts: '{{ hosts }}'
  remote_user: root
  tasks:
   - name: Install epel-release
     yum: state=present name=epel-release
     when: ansible_distribution == "CentOS"

   - name: install NRPE system updates for centos systems
     yum: state=present name={{item}}
     with_items:
       - nrpe
       - nagios-plugins  
       - nagios-plugins-nrpe
       - nagios-plugins-all
     when: ansible_distribution == "CentOS"

   - name: configuration NRPE allow host
     lineinfile: dest=/etc/nagios/nrpe.cfg regexp='^allowed_hosts=' line='allowed_hosts=127.0.0.1,74.222.139.188, 172.16.84.10' backup=yes
     when: ansible_distribution == "CentOS"

   - name: restart nrpe [CentOS 7 or Ubuntu 16]
     systemd: state=restarted name=nrpe enabled=yes
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='6'

   - name: restart nrpe [CentOS 7 or Ubuntu 14]
     service: state=restarted name=nrpe enabled=yes
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='6'

